# 每天7:08执行

name: Start

on:
   gollum:
   workflow_dispatch:
   schedule:
       - cron: '08 23 * * *'

env:
  GIT_NAME: "action@github.com"
  GIT_EMAIL: "GitHub Action"
  GITHUB_TOKEN: "${{ secrets.PERSON_TOKEN }}"

jobs:
  TSI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Clone repository
      with:
        token: "${{ secrets.PERSON_TOKEN }}"
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Create local change
      run: |
        date +%s > "/home/runner/work/tsi/tsi/run.txt"
        date +%s
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *
        git commit -m "[AuthChecker]" -a
        git push --force
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PERSON_TOKEN }}
        branch: 'master'
